from time import sleep
print('-='*35)
print('vamos saber se é possivel fazer um triangulo com as seguintes medidas')
sg1=float(input('digite o primeiro segmento'))
print('-='*35)
sg2=float(input('digite o segundo segmento'))
print('-='*35)
sg3=float(input('digite o terceiro segmento'))
print('-='*35)
print('processando.')
sleep(1)
print('processando..')
sleep(1)
print('processando...')
sleep(1)
if sg1+sg2 > sg3and sg1+sg3 > sg2 and sg2+sg3 > sg1:
 print('os segmentos acima podem formar um triangulo')
else:
    print('os segmentos acima não podem formar um triangulo')
    print('-='*35)